export default [
  {
    name: 'Hachem',
    floor: 'first',
    room: 'first',
    photo: 'img/employee1.jpg',
    place: 0,
  },
  {
    name: 'Alex',
    floor: 'first',
    room: 'first',
    photo: 'img/employee2.jpg',
    place: 3,
  },
  {
    name: 'Sergey',
    floor: 'first',
    room: 'first',
    photo: 'img/employee3.jpg',
    place: 2,
  },
  {
    name: 'Andrei',
    floor: 'first',
    room: 'first',
    photo: 'img/employee4.jpg',
    place: 1,
  },
  {
    name: 'Katerina',
    floor: 'first',
    room: 'first',
    photo: 'img/employee1.jpg',
    place: 4,
  },
  {
    name: 'Beth',
    floor: 'first',
    room: 'first',
    photo: 'img/employee2.jpg',
    place: 6,
  },
  {
    name: 'Richard',
    floor: 'first',
    room: 'first',
    photo: 'img/employee3.jpg',
    place: 5,
  },
  {
    name: 'Bima',
    floor: 'first',
    room: 'first',
    photo: 'img/employee3.jpg',
    place: 5,
  },
];
