export default [
  {
    name: 'hachem',
    floor: 'first',
    room: 'first',
    photo: 'img/employee1.jpg',
    place: 0,
  },
  {
    name: 'alex',
    floor: 'first',
    room: 'first',
    photo: 'img/employee2.jpg',
    place: 3,
  },
  {
    name: 'sergey',
    floor: 'first',
    room: 'first',
    photo: 'img/employee3.jpg',
    place: 2,
  },
  {
    name: 'andrei',
    floor: 'first',
    room: 'first',
    photo: 'img/employee4.jpg',
    place: 1,
  },
  {
    name: 'katerina',
    floor: 'first',
    room: 'first',
    photo: 'img/employee1.jpg',
    place: 4,
  },
  {
    name: 'beth',
    floor: 'first',
    room: 'first',
    photo: 'img/employee2.jpg',
    place: 6,
  },
  {
    name: 'richard',
    floor: 'first',
    room: 'first',
    photo: 'img/employee3.jpg',
    place: 5,
  },
  {
    name: 'bima',
    floor: 'first',
    room: 'first',
    photo: 'img/employee3.jpg',
    place: 5,
  },
];
